# Exception是所有程序异常类的父类
try:
    print(num)
    # print(1/0)
except Exception as result:
    print(result)